career/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recommendation_sys.urls')),
    path('personalitytest/', include(('personality.urls','personality'), namespace='personality')),

]

personality/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('test/', views.test, name="test"),
    path('result/', views.result, name="result"),
    path('take/', views.take, name='take'),
    path('take/save/', views.save, name='save'),
    path('testtwo/', views.testtwo, name='testtwo'),
    path('testtwo/testtwosave/', views.testtwosave, name='testtwosave'),
    


]

personality/models.py
from django.db import models
from account.models import student
# Create your models here.

class User_Personality(models.Model):
    Realistic = models.FloatField()
    Investigative = models.FloatField()
    Artistic = models.FloatField()
    Social = models.FloatField()
    Enterprising = models.FloatField()
    Conventional = models.FloatField()
    user_id = models.ForeignKey(student, on_delete=models.CASCADE, null=False)

class Questions(models.Model):


	Question = models.CharField(max_length=300)
	area = models.CharField(max_length=30)
	

	def __str__(self):
		return self.Question

personality/forms.py
from django import forms
import django.forms
import json



class FieldHandler():

    formfields = {}

    def __init__(self, fields):
        for field in fields:
            options = self.get_options(field)
            f = getattr(self, "create_field_for_"+field['type'] )(field, options)
            self.formfields[field['name']] = f

    def get_options(self, field):
        options = {}
        options['label'] = field['label']
        options['help_text'] = field.get("help_text", None)
        options['required'] = bool(field.get("required", 0) )
        return options

    def create_field_for_text(self, field, options):
        options['max_length'] = int(field.get("max_length", "20") )
        return django.forms.CharField(**options)

    def create_field_for_textarea(self, field, options):
        options['max_length'] = int(field.get("max_value", "9999") )
        return django.forms.CharField(widget=django.forms.Textarea, **options)

    def create_field_for_integer(self, field, options):
        options['max_value'] = int(field.get("max_value", "999999999") )
        options['min_value'] = int(field.get("min_value", "-999999999") )
        return django.forms.IntegerField(**options)

    def create_field_for_radio(self, field, options):
        options['choices'] = [ (c['value'], c['name'] ) for c in field['choices'] ]
        return django.forms.ChoiceField(widget=django.forms.RadioSelect,   **options)

    def create_field_for_select(self, field, options):
        options['choices']  = [ (c['value'], c['name'] ) for c in field['choices'] ]
        return django.forms.ChoiceField(  **options)

    def create_field_for_checkbox(self, field, options):
    	return django.forms.BooleanField(widget=django.forms.CheckboxInput, **options)


def get_form(jstr):
    fields=json.loads(jstr)
    fh = FieldHandler(fields)
    return type('DynaForm', (django.forms.Form,), fh.formfields )

personality/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import get_form
from .models import User_Personality, Questions
from account.models import student
from django.contrib.auth.models import User
# from django.contrib import messages
import json
from django.http.response import JsonResponse




@login_required(login_url='login')
def test(request):
    global a

    form_class = get_form(a)
    data = {}
    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            r = 0
            i = 0
            a = 0
            s = 0
            e = 0
            c = 0

            if form.is_valid():

                # r = int(form.cleaned_data['Realistic1']) + int(form.cleaned_data['Realistic2']) + int(form.cleaned_data['Realistic3']) + int(form.cleaned_data['Realistic4']) + int(form.cleaned_data['Realistic5']) + int(form.cleaned_data['Realistic6']) + int(form.cleaned_data['Realistic7']) + int(form.cleaned_data['Realistic8']) + int(form.cleaned_data['Realistic9']) + int(form.cleaned_data['Realistic10'])

                # i = int(form.cleaned_data['Investigative1']) + int(form.cleaned_data['Investigative2']) + int(form.cleaned_data['Investigative3'])+ int(form.cleaned_data['Investigative4']) + int(form.cleaned_data['Investigative5']) + int(form.cleaned_data['Investigative6']) + int(form.cleaned_data['Investigative10'])

                # a = int(form.cleaned_data['Artistic1']) + int(form.cleaned_data['Artistic2']) + int(form.cleaned_data['Artistic3'])+ int(form.cleaned_data['Artistic4']) + int(form.cleaned_data['Artistic5']) + int(form.cleaned_data['Artistic6']) + int(form.cleaned_data['Artistic7']) + int(form.cleaned_data['Artistic8']) + int(form.cleaned_data['Artistic9']) + int(form.cleaned_data['Artistic10'])

                # s = int(form.cleaned_data['Social1']) + int(form.cleaned_data['Social2']) + int(form.cleaned_data['Social3'])+ int(form.cleaned_data['Social4']) + int(form.cleaned_data['Social5']) + int(form.cleaned_data['Social6']) +int(form.cleaned_data['Social7']) + int(form.cleaned_data['Social8']) + int(form.cleaned_data['Social9']) +int(form.cleaned_data['Social10'])

                # e = int(form.cleaned_data['Enterprising1']) + int(form.cleaned_data['Enterprising2']) + int(form.cleaned_data['Enterprising3'])+ int(form.cleaned_data['Enterprising4']) + int(form.cleaned_data['Enterprising5']) + int(form.cleaned_data['Enterprising6']) + int(form.cleaned_data['Enterprising7']) + int(form.cleaned_data['Enterprising8']) + int(form.cleaned_data['Enterprising9']) + int(form.cleaned_data['Enterprising10'])

                # c = int(form.cleaned_data['Conventional1']) + int(form.cleaned_data['Conventional2']) + int(form.cleaned_data['Conventional3'])+ int(form.cleaned_data['Conventional4']) + int(form.cleaned_data['Conventional5']) + int(form.cleaned_data['Conventional6']) + int(form.cleaned_data['Conventional7']) + int(form.cleaned_data['Conventional8']) + int(form.cleaned_data['Conventional9']) + int(form.cleaned_data['Conventional10'])

                r = int(form.cleaned_data['Realistic1']) + \
                    int(form.cleaned_data['Realistic2'])
                i = int(form.cleaned_data['Investigative1']) + \
                    int(form.cleaned_data['Investigative2'])
                a = int(form.cleaned_data['Artistic1']) + \
                    int(form.cleaned_data['Artistic2'])
                s = int(form.cleaned_data['Social1']) + \
                    int(form.cleaned_data['Social2'])
                e = int(form.cleaned_data['Enterprising1']) + \
                    int(form.cleaned_data['Enterprising2'])
                c = int(form.cleaned_data['Conventional1']) + \
                    int(form.cleaned_data['Conventional2'])
                user = User.objects.get(username=request.user.get_username())

                try:

                    person = student.objects.get(Identification_no=user)
                    user_pers, created = User_Personality.objects.update_or_create(user_id=person, defaults={
                                                                                   'Realistic': r/5, 'Investigative': i/5, 'Artistic': a/5, 'Social': s/5, 'Enterprising': e/5, 'Conventional': c/5, })
                    print(user_pers)

                    # user_pers.Realistic = r/5
                    # user_pers.Investigative = i/5
                    # user_pers.Artistic = a/5
                    # user_pers.Social = s/5
                    # user_pers.Enterprising = e/5
                    # user_pers.Conventional = c/5

                    # user_pers.save()
                    return redirect('result')

                except:
                    return render(request, 'personality/test.html')

        return redirect('personality/test')

    else:
        form = form_class()

    context = {'form': form,  'data': data,
               'profile_test': 'active', 'crumb': 'Profile Test', }

    return render(request, "personality/test.html", context)


@login_required(login_url='login')
def result(request):
    u = User.objects.get(username=request.user.get_username())
    person = student.objects.get(Identification_no=u)
    message = ''
    results = None
    record = []

    if User_Personality.objects.filter(user_id=person):
        results = list(User_Personality.objects.filter(
            user_id=person).values())
        record.append(results[0]['Realistic'])
        record.append(results[0]['Investigative'])
        record.append(results[0]['Artistic'])
        record.append(results[0]['Social'])
        record.append(results[0]['Enterprising'])
        record.append(results[0]['Conventional'])

    else:
        return redirect('personality/test')

    context = {'student': student,
               'results': record,
               'message': message,
               'profile_test': 'active',
               'Realistic': record[0],
               'Investigative':record[1],
               'Artistic':record[2],
               'Social': record[3],
               'Enterprising':record[4],
               'Conventional': record[5],

               'crumb': 'Profile Test'}
    print(results, record, "uu")

    return render(request, 'personality/result.html', context)


def take(request):
    try:
        # child_user = Child.objects.get(user=request.user)

        quiz_words = Questions.objects.all()
        area_list = []

        wordList = []
        for items in quiz_words:
            wordList.append(str(items))

        for items in quiz_words:

            area_list.append(str(items.area))


        context = {
            # 'newuser': child_user,
            'word': quiz_words,
            'data': wordList,
            'area': area_list,
            # 'wordlimit': wordlimit,
        }
        return render(request, 'personality/take.html', context)
    except:

        return render(request, 'personality/take.html', {})

def save(request):
    if request.method == 'POST':
        u = User.objects.get(username=request.user.get_username())
        person = student.objects.get(Identification_no=u)
        Realistic = int(request.POST.get('Realistic'))
        Investigative = int(request.POST.get('Investigative'))
        Artistic = int(request.POST.get('Artistic'))
        Social = int(request.POST.get('Social'))
        Enterprising = int(request.POST.get('Enterprising'))
        Conventional = int(request.POST.get('Conventional'))

        result_url = reverse('personality:result')

        
        print(result_url)
        print()


        print(person)
        try:

            # person = student.objects.get(Identification_no=person)
            print(person)
            user_pers, created = User_Personality.objects.update_or_create(user_id=person, defaults={
                                                                           'Realistic': Realistic, 'Investigative': Investigative, 'Artistic': Artistic, 'Social': Social, 'Enterprising': Enterprising, 'Conventional': Conventional, })
            print('hello', user_pers)

            
            return JsonResponse(status=302, data={"url": request.build_absolute_uri(result_url)})

            # return redirect('personalitytest:test')
            # return JsonResponse({'status': 'success'})

        except :
            # print(e)
            print('bye', user_pers)
            print(request)
            return render(request, 'personality/test.html')
    return render(request, 'personality/test.html')



def testtwo(request):
    try:
        # child_user = Child.objects.get(user=request.user)

        quiz_words = Questions.objects.all()
        area_list = []

        wordList = []
        for items in quiz_words:
            wordList.append(str(items))

        for items in quiz_words:

            area_list.append(str(items.area))


        context = {
            # 'newuser': child_user,
            'word': quiz_words,
            'data': wordList,
            'area': area_list,
            # 'wordlimit': wordlimit,
        }
        return render(request, 'personality/testtwo.html', context)
    except:
  
        return render(request, 'personality/testtwo.html', {})

def testtwosave(request):
    if request.method == 'POST':
        u = User.objects.get(username=request.user.get_username())
        person = student.objects.get(Identification_no=u)
        Realistic = int(request.POST.get('Realistic'))
        Investigative = int(request.POST.get('Investigative'))
        Artistic = int(request.POST.get('Artistic'))
        Social = int(request.POST.get('Social'))
        Enterprising = int(request.POST.get('Enterprising'))
        Conventional = int(request.POST.get('Conventional'))

        result_url = reverse('personality:result')

        
        print(result_url)
        print()


        print(person)
        try:

personality/templates/personality/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>
    <!-- Prevent the demo from appearing in search engines -->
    <meta name="robots" content="noindex">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700%7CRoboto:400,500%7CExo+2:600&display=swap" rel="stylesheet">
    <!-- Perfect Scrollbar -->
    <!-- Perfect Scrollbar -->
    <link type="text/css" href="{% static 'css/perfect-scrollbar.css' %}" rel="stylesheet">
    <!-- Fix Footer CSS -->
    <link type="text/css" href="{% static 'css/fix-footer.css' %}" rel="stylesheet">
    <!-- Material Design Icons -->
    <link type="text/css" href="{% static 'css/material-icons.css' %}" rel="stylesheet">
    <!-- Font Awesome Icons -->
    <link type="text/css" href="{% static 'css/fontawesome.css' %}" rel="stylesheet">
    <!-- Preloader -->
    <link type="text/css" href="{% static 'css/preloader.css' %}" rel="stylesheet">
    <!-- App CSS -->
    <link type="text/css" href="{% static 'css/app.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'personality/questions.css' %}" rel="stylesheet">
    <style type="text/css">
    .show {
        color: black !important;
    }
    </style>
</head>

<body class="layout-app ">
    <div class="preloader">
        <div class="sk-double-bounce">
            <div class="sk-child sk-double-bounce1"></div>
            <div class="sk-child sk-double-bounce2"></div>
        </div>
    </div>
    </div>
    <div class="mdk-drawer-layout js-mdk-drawer-layout" data-push data-responsive-width="992px">
        <div class="mdk-drawer-layout__content page-content">
            <!-- Header -->
            <div class="navbar navbar-expand pr-0 navbar-light border-bottom-2" id="default-navbar" data-primary>
                <!-- Navbar toggler -->
                <button class="navbar-toggler w-auto mr-16pt d-block d-lg-none rounded-0" type="button" data-toggle="sidebar">
                    <span class="material-icons">short_text</span>
                </button>
                <!-- Navbar Brand -->
                <a href="" class="navbar-brand mr-16pt d-lg-none">
                    <span class="avatar avatar-sm navbar-brand-icon mr-0 mr-lg-8pt">
                    </span>
                    <span class="d-none d-lg-block">CAP framework</span>
                </a>
                <div class="flex"></div>
                <div class="nav navbar-nav flex-nowrap d-flex mr-16pt">
                </div>
            </div>
            <!-- // END Header -->
            <div class="pt-32pt">
                <div class="container page__container d-flex flex-column flex-md-row align-items-center text-center text-sm-left">
                    <div class="flex d-flex flex-column flex-sm-row align-items-center mb-24pt mb-md-0">
                        <div class="mb-24pt mb-sm-0 mr-sm-24pt">
                            <h2 class="mb-0">Dashboard</h2>
                            <ol class="breadcrumb p-0 m-0">
                                <li class="breadcrumb-item"><a href="{% url 'studentdashboard' %}">Home</a></li>
                                <li class="breadcrumb-item active">
                                    {{crumb}}
                                </li>
                            </ol>
                        </div>
                    </div>
                    <div class="row" role="tablist">
                        <div class="col-auto">
                            <a href="#" onclick="history.back()" class="btn btn-outline-secondary" id="backbtn">Go back</a>
                        </div>
                    </div>
                </div>
            </div>
            {% block body_block %}
            {% endblock %}
        </div>
        <!-- // END drawer-layout__content -->
        <!-- drawer -->
        <div class="mdk-drawer js-mdk-drawer" id="default-drawer">
            <div class="mdk-drawer__content">
                <div class="sidebar sidebar-dark-dodger-blue sidebar-left" data-perfect-scrollbar>
                    <div class="d-flex align-items-center navbar-height">
                    </div>
                    <a href="index.html" class="sidebar-brand ">
                        <!-- <img class="sidebar-brand-icon" src="assets/images/illustration/teacher/128/white.svg" alt="Luma"> -->
                        CAP Framework
                    </a>
                    <div class="sidebar-heading">Student</div>
                    <ul class="sidebar-menu">
                        <li class="sidebar-menu-item {{student_dashboard}}">
                            <a class="sidebar-menu-button" href="{% url 'studentdashboard' %}">
                                <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">school</span>
                                <span class="sidebar-menu-text">Home</span>
                            </a>
                        </li>
                        <li class="sidebar-menu-item">
                            <a class="sidebar-menu-button collapsed" data-toggle="collapse" href="#productivity_menu" aria-expanded="false">
                                <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">dvr</span>
                                Take Personality Test
                                <span class="ml-auto sidebar-menu-toggle-icon"></span>
                            </a>
                            <ul class="sidebar-submenu sm-indent collapse" id="productivity_menu" style="">
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'personality:take' %}">
                                        <span class="sidebar-menu-text">one by one</span>
                                    </a>
                                </li>
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'personality:testtwo' %}">
                                        <span class="sidebar-menu-text">groups of 12</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-menu-item {{recomm_career}}">
                            <a class="sidebar-menu-button" href="{% url 'personality:result' %}">
                                <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">help</span>
                                <span class="sidebar-menu-text">Profile Result</span>
                            </a>
                        </li>
                        <li class="sidebar-menu-item ">
                            <a class="sidebar-menu-button js-sidebar-collapse" data-toggle="collapse" href="#enterprise_menu" aria-expanded="true">
                                <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">donut_large</span>
                                Recommend Career
                                <span class="ml-auto sidebar-menu-toggle-icon"></span>
                            </a>
                            <ul class="sidebar-submenu sm-indent collapse show" id="enterprise_menu" style="">
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'rankings' %}">
                                        <span class="sidebar-menu-text">Overall Rankings</span>
                                    </a>
                                </li>
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'rankings_acad' %}">
                                        <span class="sidebar-menu-text">Transcript alone</span>
                                    </a>
                                </li>
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'rankings_pers' %}">
                                        <span class="sidebar-menu-text">Personality alone</span>
                                    </a>
                                </li>
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'rankings_both' %}">
                                        <span class="sidebar-menu-text">Transcript and Personality</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- // END drawer-layout -->
        <!-- jQuery -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <!-- Bootstrap -->
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- Perfect Scrollbar -->
        <script src="{% static 'js/perfect-scrollbar.min.js' %}"></script>
        <!-- DOM Factory -->
        <script src="{% static 'js/dom-factory.js' %}"></script>
        <!-- MDK -->
        <script src="{% static 'js/material-design-kit.js' %}"></script>
        <!-- Fix Footer -->
        <script src="{% static 'js/fix-footer.js' %}"></script>
        <!-- App JS -->
        <script src="{% static 'js/app.js' %}"></script>
        <!-- Global Settings -->
        <script src="{% static 'js/settings.js' %}"></script>
        <!-- Moment.js -->
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/moment-range.min.js' %}"></script>
        <!-- Chart.js -->
        <script src="{% static 'js/Chart.min.js' %}"></script>
        <!-- UI Charts Page JS -->
        <script src="{% static 'js/chartjs-rounded-bar.js' %}"></script>
        <script src="{% static 'js/chartjs.js' %}"></script>
        <!-- Chart.js Samples -->
        <script src="{% static 'js/page.instructor-dashboard.js' %}"></script>
        <!-- List.js -->
        <script src="{% static 'js/list.min.js' %}"></script>
        <script src="{% static 'js/list.js' %}"></script>
</body>

</html>

personality/templates/personality/result.html
{% extends "personality/base.html" %}
{% load static %}
{% block body_block %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!-- Chart js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<div class="page-section border-bottom-2">
    <div class="container page__container">
        <div class="row">
            <div class="col-lg-4">
                <div class="card border-1 border-left-3 border-left-accent text-center mb-lg-0">
                    <div class="card-body">
                        <h4 class="h2 mb-0">{{Realistic}}</h4>
                        <div>Realistic</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card text-center mb-lg-0">
                    <div class="card-body">
                        <h4 class="h2 mb-0">{{Investigative}}</h4>
                        <div>Investigative</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card text-center mb-lg-0">
                    <div class="card-body">
                        <h4 class="h2 mb-0">{{Artistic}}</h4>
                        <div>Artisitic</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-separator" style="visibility:hidden">
        {# <div class="page-separator__text">Result</div> #}
    </div>
    <div class="container page__container">
        <div class="row">
            <div class="col-lg-4">
                <div class="card border-1 border-left-3 border-left-accent text-center mb-lg-0">
                    <div class="card-body">
                        <h4 class="h2 mb-0">{{Social}}</h4>
                        <div>Social</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card text-center mb-lg-0">
                    <div class="card-body">
                        <h4 class="h2 mb-0">{{Enterprising}}</h4>
                        <div>Enterprising</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card text-center mb-lg-0">
                    <div class="card-body">
                        <h4 class="h2 mb-0">{{Conventional}}</h4>
                        <div>Conventional</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="page-section border-bottom-2">
    <div class="container page__container">
        <div class="row align-items-start">
            <div class="col-md-8">
                <div class="page-separator">
                    <div class="page-separator__text">Result</div>
                </div>
                <ul class="list-group stack mb-40pt">
                    <li class="list-group-item d-flex">
                        <canvas id="myChart" width="400" height="250"></canvas>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <div class="page-separator">
                    <div class="page-separator__text">Test</div>
                </div>
                <div class="card">
                    <div class="card-body text-center">
                        <a href="{% url 'personality:testtwo' %}" class="btn btn-accent">Retake</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ChartJS -->
<script src="{% static 'personality/chart.js/Chart.min.js' %}"></script>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',

    data: {
        labels: ['Realistic', 'Investigative', 'Artistic', 'Social', 'Enterprising', 'Conventional'],
        datasets: [{
            label: 'Interest Profile - Result',
            // data: [12, 19, 3, 5, 2, 3],
            data: { { results } },
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }],

    },
    options: {
        indexAxis: 'y',
        scales: {
            'y': {
                beginAtZero: true
            }
        },
        // maintainAspectRatio: false,
        // responsive: true,
    }

});
</script>
{% endblock body_block %}

personality/templates/personality/test.html
{% extends "personality/base.html" %}

{% block body_block %}
<div class="container page__container page-section">
  <div class="card card-body mb-32pt">
    <form role="form" method="POST" action="{% url 'personality:test' %}" enctype="multipart/form-data">
      {% csrf_token %}
      {{form}}
      <button type="submit" class="btn btn-primary">{{ "Add" }}</button>
    </form>
  </div>
</div>

{% endblock body_block %}