career/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recommendation_sys.urls')),
    path('personalitytest/', include(('personality.urls','personality'), namespace='personality')),

]

personality/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('test/', views.test, name="test"),
    path('result/', views.result, name="result"),
    path('take/', views.take, name='take'),
    path('take/save/', views.save, name='save'),
    path('testtwo/', views.testtwo, name='testtwo'),
    path('testtwo/testtwosave/', views.testtwosave, name='testtwosave'),
    


]

recommendation_sys/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('/a', views.index, name='index'),
	path('', views.indexx, name='indexx'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('studentdashboard/', views.studentdashboard, name='studentdashboard'),
    path('rankings/', views.rankings, name='rankings'),
    path('rankings_acad/', views.rankings_acad, name='rankings_acad'),
    path('rankings_pers/', views.rankings_pers, name='rankings_pers'),
    path('rankings_both/', views.rankings_both, name='rankings_both'),
    

]

recommendation_sys/models.py
from django.db import models

# Create your models here.

recommendation_sys/views.py
from django.shortcuts import render, redirect
from .weighted_scoring_model import career_know_skill_personality, career_acad, career_person
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from account.models import student
from personality.models import User_Personality

# Create your views here.


def index(request):
    return render(request, 'recommendation_sys/index.html')

def indexx(request):
    return render(request, 'recommendation_sys/indexx.html')

def login(request):
    if request.method == 'POST':
        user = auth.authenticate(
            username=request.POST['username'], password=request.POST['password'])

        if user is not None and student.objects.get(Identification_no=user):
            auth.login(request, user)
            return redirect('studentdashboard')

        else:
            message = 'Incorrect Login Details'
            return render(request, 'recommendation_sys/login.html', {'message': message})
    else:
        return render(request, 'recommendation_sys/login.html')


def logout(request):
    auth.logout(request)
    return redirect('login')


@login_required(login_url='login')
def studentdashboard(request):
    user = User.objects.get(username=request.user.get_username())
    stud = student.objects.get(Identification_no=user)
    student_id = str(stud.id-1)
    personality = None

    if User_Personality.objects.filter(user_id=stud):
        personality = User_Personality.objects.filter(user_id=stud)

    context = {
        'personality': personality,
        'student': stud,
        'student_dashboard': 'active',
        'crumb': 'Student Dashboard',
    }

    return render(request, 'recommendation_sys/studentdashboard.html', context)


@login_required(login_url='login')
def rankings(request):

    u = User.objects.get(username=request.user.get_username())
    person = student.objects.get(Identification_no=u)
    student_id = str(person.id-1)
    results = None
    record = [0.0 for i in range(6)]

    if User_Personality.objects.filter(user_id=person):
        results = list(User_Personality.objects.filter(
            user_id=person).values())
        record[0] = results[0]['Realistic']
        record[1] = results[0]['Investigative']
        record[2] = results[0]['Artistic']
        record[3] = results[0]['Social']
        record[4] = results[0]['Enterprising']
        record[5] = results[0]['Conventional']

    student_id = str(person.id-1)
    # careerdes_KS, rankings_KS = career_acad('0')
    # careerdes_P,rankings_P = career_person('0', record)
    # careerdes_KSP,rankings_KSP = career_know_skill_personality('0', record)

    # careerdes_KS, rankings_KS = career_acad('0')
    # careerdes_P,rankings_P = career_person('0', record)
    # careerdes_KSP,rankings_KSP = career_know_skill_personality('0', record)
    context = {

        
        "rankings_P": career_person(student_id, record)[:2],
        "rankings_KSP": career_know_skill_personality(student_id, record)[:2],
        "rankings_KS": career_acad(student_id)[:2],

        'recomm_career': 'active',
        'crumb': 'Recommend Career',
    }
    return render(request, "recommendation_sys/rankings.html", context)


@login_required(login_url='login')
def rankings_acad(request):

    u = User.objects.get(username=request.user.get_username())
    person = student.objects.get(Identification_no=u)
    student_id = str(person.id-1)
    # results = None
    # record = [0.0 for i in range(6)]

    # if User_Personality.objects.filter(user_id=person):
    #     results = list(User_Personality.objects.filter(
    #         user_id=person).values())
    #     record[0] = results[0]['Realistic']
    #     record[1] = results[0]['Investigative']
    #     record[2] = results[0]['Artistic']
    #     record[3] = results[0]['Social']
    #     record[4] = results[0]['Enterprising']
    #     record[5] = results[0]['Conventional']

    context = {

        "rankings_KS": career_acad(student_id)

    }
    return render(request, "recommendation_sys/rankings_acad.html", context)


@login_required(login_url='login')
def rankings_pers(request):

    u = User.objects.get(username=request.user.get_username())
    person = student.objects.get(Identification_no=u)
    student_id = str(person.id-1)
    results = None
    record = [0.0 for i in range(6)]

    if User_Personality.objects.filter(user_id=person):
        results = list(User_Personality.objects.filter(
            user_id=person).values())
        record[0] = results[0]['Realistic']/5
        record[1] = results[0]['Investigative']/5
        record[2] = results[0]['Artistic']/5
        record[3] = results[0]['Social']/5
        record[4] = results[0]['Enterprising']/5
        record[5] = results[0]['Conventional']/5

    context = {


        "rankings_P": career_person(student_id, record),

    }
    return render(request, "recommendation_sys/rankings_pers.html", context)


@login_required(login_url='login')
def rankings_both(request):

    u = User.objects.get(username=request.user.get_username())
    person = student.objects.get(Identification_no=u)
    results = None
    record = [0.0 for i in range(6)]
    student_id = str(person.id-1)
    if User_Personality.objects.filter(user_id=person):
        results = list(User_Personality.objects.filter(
            user_id=person).values())
        record[0] = results[0]['Realistic']/5
        record[1] = results[0]['Investigative']/5
        record[2] = results[0]['Artistic']/5
        record[3] = results[0]['Social']/5
        record[4] = results[0]['Enterprising']/5
        record[5] = results[0]['Conventional']/5

    context = {

        "rankings_KSP": career_know_skill_personality(student_id, record),

    }
    return render(request, "recommendation_sys/rankings_both.html", context)

recommendation_sys/templates/recommendation_sys/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>
    <!-- Prevent the demo from appearing in search engines -->
    <meta name="robots" content="noindex">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700%7CRoboto:400,500%7CExo+2:600&display=swap" rel="stylesheet">
    <!-- Perfect Scrollbar -->
    <!-- Perfect Scrollbar -->
    <link type="text/css" href="{% static 'css/perfect-scrollbar.css' %}" rel="stylesheet">
    <!-- Fix Footer CSS -->
    <link type="text/css" href="{% static 'css/fix-footer.css' %}" rel="stylesheet">
    <!-- Material Design Icons -->
    <link type="text/css" href="{% static 'css/material-icons.css' %}" rel="stylesheet">
    <!-- Font Awesome Icons -->
    <link type="text/css" href="{% static 'css/fontawesome.css' %}" rel="stylesheet">
    <!-- Preloader -->
    <link type="text/css" href="{% static 'css/preloader.css' %}" rel="stylesheet">
    <!-- App CSS -->
    <link type="text/css" href="{% static 'css/app.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'personality/questions.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'css/ranking.css' %}" rel="stylesheet">
    <style type="text/css">
    .show {
        color: black !important;
    }
    </style>
</head>

<body class="layout-app ">
    <div class="preloader">
        <div class="sk-double-bounce">
            <div class="sk-child sk-double-bounce1"></div>
            <div class="sk-child sk-double-bounce2"></div>
        </div>
    </div>
    </div>
    <div class="mdk-drawer-layout js-mdk-drawer-layout" data-push data-responsive-width="992px">
        <div class="mdk-drawer-layout__content page-content">
            <!-- Header -->
            <div class="navbar navbar-expand pr-0 navbar-light border-bottom-2" id="default-navbar" data-primary>
                <!-- Navbar toggler -->
                <button class="navbar-toggler w-auto mr-16pt d-block d-lg-none rounded-0" type="button" data-toggle="sidebar">
                    <span class="material-icons">short_text</span>
                </button>
                <!-- Navbar Brand -->
                <a href="" class="navbar-brand mr-16pt d-lg-none">
                    <span class="avatar avatar-sm navbar-brand-icon mr-0 mr-lg-8pt">
                    </span>
                    <span class="d-none d-lg-block">CAP framework</span>
                </a>
                <div class="flex"></div>
                <div class="nav navbar-nav flex-nowrap d-flex mr-16pt">
                </div>
            </div>
            <!-- // END Header -->
            <div class="pt-32pt">
                <div class="container page__container d-flex flex-column flex-md-row align-items-center text-center text-sm-left">
                    <div class="flex d-flex flex-column flex-sm-row align-items-center mb-24pt mb-md-0">
                        <div class="mb-24pt mb-sm-0 mr-sm-24pt">
                            <h2 class="mb-0">Dashboard</h2>
                            <ol class="breadcrumb p-0 m-0">
                                <li class="breadcrumb-item"><a href="{% url 'studentdashboard' %}">Home</a></li>
                                <li class="breadcrumb-item active">
                                    {{crumb}}
                                </li>
                            </ol>
                        </div>
                    </div>
                    <div class="row" role="tablist">
                        <div class="col-auto">
                            <a href="#" onclick="history.back()" id="backbtn" class="btn btn-outline-secondary">Go back</a>
                        </div>
                    </div>
                </div>
            </div>
            {% block body_block %}
            {% endblock %}
        </div>
        <!-- // END drawer-layout__content -->
        <!-- drawer -->
        <div class="mdk-drawer js-mdk-drawer" id="default-drawer">
            <div class="mdk-drawer__content">
                <div class="sidebar sidebar-dark-dodger-blue sidebar-left" data-perfect-scrollbar>
                    <div class="d-flex align-items-center navbar-height">
                    </div>
                    <a href="index.html" class="sidebar-brand ">
                        <!-- <img class="sidebar-brand-icon" src="assets/images/illustration/teacher/128/white.svg" alt="Luma"> -->
                        CAP Framework
                    </a>
                    <div class="sidebar-heading">Student</div>
                    <ul class="sidebar-menu">
                        <li class="sidebar-menu-item {{student_dashboard}}">
                            <a class="sidebar-menu-button" href="{% url 'studentdashboard' %}">
                                <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">school</span>
                                <span class="sidebar-menu-text">Home</span>
                            </a>
                        </li>
                        <li class="sidebar-menu-item">
                            <a class="sidebar-menu-button collapsed" data-toggle="collapse" href="#productivity_menu" aria-expanded="false">
                                <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">dvr</span>
                                Take Personality Test
                                <span class="ml-auto sidebar-menu-toggle-icon"></span>
                            </a>
                            <ul class="sidebar-submenu sm-indent collapse" id="productivity_menu" style="">
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'personality:take' %}">
                                        <span class="sidebar-menu-text">one by one</span>
                                    </a>
                                </li>
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'personality:testtwo' %}">
                                        <span class="sidebar-menu-text">groups of 12</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="sidebar-menu-item {{recomm_career}}">
                            <a class="sidebar-menu-button" href="{% url 'personality:result' %}">
                                <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">help</span>
                                <span class="sidebar-menu-text">Profile Result</span>
                            </a>
                        </li>
                        <li class="sidebar-menu-item ">
                            <a class="sidebar-menu-button js-sidebar-collapse" data-toggle="collapse" href="#enterprise_menu" aria-expanded="true">
                                <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">donut_large</span>
                                Recommend Career
                                <span class="ml-auto sidebar-menu-toggle-icon"></span>
                            </a>
                            <ul class="sidebar-submenu sm-indent collapse show" id="enterprise_menu" style="">
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'rankings' %}">
                                        <span class="sidebar-menu-text">Overall Rankings</span>
                                    </a>
                                </li>
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'rankings_acad' %}">
                                        <span class="sidebar-menu-text">Transcript alone</span>
                                    </a>
                                </li>
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'rankings_pers' %}">
                                        <span class="sidebar-menu-text">Personality alone</span>
                                    </a>
                                </li>
                                <li class="sidebar-menu-item">
                                    <a class="sidebar-menu-button" href="{% url 'rankings_both' %}">
                                        <span class="sidebar-menu-text">Transcript and Personality</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- // END drawer-layout -->
        <!-- jQuery -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <!-- Bootstrap -->
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- Perfect Scrollbar -->
        <script src="{% static 'js/perfect-scrollbar.min.js' %}"></script>
        <!-- DOM Factory -->
        <script src="{% static 'js/dom-factory.js' %}"></script>
        <!-- MDK -->
        <script src="{% static 'js/material-design-kit.js' %}"></script>
        <!-- Fix Footer -->
        <script src="{% static 'js/fix-footer.js' %}"></script>
        <!-- App JS -->
        <script src="{% static 'js/app.js' %}"></script>
        <!-- Global Settings -->
        <script src="{% static 'js/settings.js' %}"></script>
        <!-- Moment.js -->
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/moment-range.min.js' %}"></script>
        <!-- Chart.js -->
        <script src="{% static 'js/Chart.min.js' %}"></script>
        <!-- UI Charts Page JS -->
        <script src="{% static 'js/chartjs-rounded-bar.js' %}"></script>
        <script src="{% static 'js/chartjs.js' %}"></script>
        <!-- Chart.js Samples -->
        <script src="{% static 'js/page.instructor-dashboard.js' %}"></script>
        <!-- List.js -->
        <script src="{% static 'js/list.min.js' %}"></script>
        <script src="{% static 'js/list.js' %}"></script>
</body>

</html>

recommendation_sys/templates/recommendation_sys/indexx.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>update</title>
    <link rel="stylesheet" href={% static "/static/bootstrap/css/bootstrap.min.css" %}>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rubik:400,500,700">
    <link rel="stylesheet" href={% static "/static/fonts/fontawesome-all.min.css" %}>
    <link rel="stylesheet" href={% static "/static/fonts/font-awesome.min.css" %}>
    <link rel="stylesheet" href={% static "/static/fonts/fontawesome5-overrides.min.css" %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href={% static "/static/css/Navigation-with-Button.css" %}>
</head>

<body style="background: white;padding: 20px;margin: 10px;">
    <nav class="navbar navbar-light navbar-expand-md navigation-clean-button" style="margin: 20px;margin-top: 35px;font-family: Rubik, sans-serif;font-style: normal;font-weight: bold;height: 75px;padding-top: 29px;padding-right: -50px;">
        <div class="container"><a class="navbar-brand" href="#" style="margin-left: -40px;">Cap Framework</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div
                class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                </ul><span class="navbar-text actions"> <a class="login" href="#" style="border-color: #0d0d2b;margin-right: 50px;"></a>
                    <a class="btn btn-light text-center action-button" role="button" href="{% url 'login' %}" style="background: #2b076e99;width: 140px;height: 40px;text-align: center;border-radius: 32px;padding: 6px 10px;font-size: 16px;">Login</a></span></div>
        </div>
    </nav>
    <div class="container" style="border-radius: 32px;margin: 20px;padding-right: 0px;margin-right: 0px;"><img class="img-fluid float-right" data-bs-hover-animate="pulse" src={% static "/static/img/amico.svg" %} style="width: 668px;margin: 20px;height: 508px;margin-right: -99px;margin-top: -17px;">
        <div style="width: 588px;height: 468px;margin-top: 0px;padding-right: 163;padding-left: 20px;margin-left: 34px;">
            <p style="color: #2b076e;margin-top: 66px;padding-top: 53px;"><span style="width: 92px;height: 24px;font-family: Rubik, sans-serif;font-weight: normal;font-style: normal;color: #000000;margin-right: 15px;">100% SAVE</span>For the Personalised Careers</p>
            <h1 style="color: #2b076e;font-family: Rubik, sans-serif;font-weight: bold;font-style: normal;font-size: 72px;width: 588px;height: 152px;margin-top: 40px;padding-top: -12px;"><strong>Secure your Future Now!</strong></h1>
            <p style="color: #2b076e;width: 435px;height: 56px;font-size: 16px;font-family: Rubik, sans-serif;font-weight: normal;font-style: normal;text-align: left;margin-top: 56px;padding-top: -140px;">Get ranked career suggestions that identifies with your strength and Weakeness</p></div>
        <div></div>
    </div>
    <div></div>
    <script src={% static "/static/js/jquery.min.js" %}></script>
    <script src={% static "/static/bootstrap/js/bootstrap.min.js" %}></script>
    <script src={% static "/static/js/chart.min.js" %}></script>
    <script src={% static "/static/js/bs-init.js" %}></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src={% static "/static/js/theme.js" %}></script>
</body>

</html>

recommendation_sys/templates/recommendation_sys/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Login</title>

  <!-- Prevent the demo from appearing in search engines -->
  <meta name="robots" content="noindex">

  <link href="https://fonts.googleapis.com/css?family=Lato:400,700%7CRoboto:400,500%7CExo+2:600&display=swap"
    rel="stylesheet">

  <!-- Perfect Scrollbar -->
  <link type="text/css" href="{% static 'vendor/perfect-scrollbar.css' %}" rel="stylesheet">

  <!-- Fix Footer CSS -->
  <link type="text/css" href="{% static 'vendor/fix-footer.css' %}" rel="stylesheet">

  <!-- Material Design Icons -->
  <link type="text/css" href="{% static 'css/material-icons.css' %}" rel="stylesheet">

  <!-- Font Awesome Icons -->
  <link type="text/css" href="{% static 'css/fontawesome.css' %}" rel="stylesheet">

  <!-- Preloader -->
  <link type="text/css" href="{% static 'css/preloader.css' %}" rel="stylesheet">

  <!-- App CSS -->
  <link type="text/css" href="{% static 'css/app.css' %}" rel="stylesheet">

</head>

<body class="layout-default layout-login-centered-boxed" style="padding-top: 150px;">

  <div class="layout-login-centered-boxed__form card">
    <div class="d-flex flex-column justify-content-center align-items-center mt-2 mb-5 navbar-light">
      <a href="learnly-index.html" class="navbar-brand flex-column mb-2 align-items-center mr-0" style="min-width: 0" style="
    text-align: center;
    padding-right: 110px;">

        <span class="avatar avatar-sm navbar-brand-icon mr-0" style="
    text-align: center;
    padding-right: 110px;
">

  
        </span>

        CAP Framework
      </a>
      <p class="m-0">Login to access your CAP Framework Account </p>
    </div>

    <form action="{% url 'login' %}" method="post" >
      {% csrf_token %}
      <div class="form-group">
        <label class="text-label" for="username">Username::</label>
        <div class="input-group input-group-merge">
          <input type="text" name="username" placeholder="Username" class="form-control form-control-prepended">
          <div class="input-group-prepend">
            <div class="input-group-text">
              <span class="far fa-envelope"></span>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label class="text-label" for="password">Password:</label>
        <div class="input-group input-group-merge">
          <input type="password" name="password" required="" class="form-control form-control-prepended"
            placeholder="Enter your password">
          <div class="input-group-prepend">
            <div class="input-group-text">
              <span class="fa fa-key"></span>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <button class="btn btn-block btn-primary" type="submit">Login</button>
        <!-- <input type="submit" name="" value="Login"> -->
    </form>
  </div>


  <!-- jQuery -->
  <script src="{% static 'vendor/jquery.min.js' %}"></script>

  <!-- Bootstrap -->
  <script src="{% static 'vendor/popper.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap.min.js' %}"></script>

  <!-- Perfect Scrollbar -->
  <script src="{% static 'vendor/perfect-scrollbar.min.js' %}"></script>

  <!-- DOM Factory -->
  <script src="{% static 'vendor/dom-factory.js' %}"></script>

  <!-- MDK -->
  <script src="{% static 'vendor/material-design-kit.js' %}"></script>

  <!-- Fix Footer -->
  <script src="{% static 'vendor/fix-footer.js' %}"></script>

  <!-- App JS -->
  <script src="{% static 'js/app.js' %}"></script>


</body>

</html>

recommendation_sys/templates/recommendation_sys/rankings.html
{% extends "recommendation_sys/base.html" %}
{% load static %}
<link type="text/css" href="{% static 'css/ranking.css' %}" rel="stylesheet">
{% block body_block %}
<div>
    {% if rankings_KS %}
    <div class="page-separator">
        <div class="page-separator__text">Academic Performance</div>
    </div>
    {% for index, rank, des in rankings_KS %}
    <div class="courses-container">
        <div class="course">
            <div class="course-preview">
                <h6 style="color: #ffffff;font-size: 1.3rem;">#{{index}}</h6>
                <h2 class="" style="color: #ffffff; font-size: 1.5rem;">{{rank}}</h2>
            </div>
            <div class="course-info">
                <h6>Description</h6>
                <h2 class="rank-h2 text" style="
    font-size: 1.2em;margin-block-start: 0.83em; margin-block-end: 0.83em; margin-inline-start: 0px;margin-inline-end: 0px;font-weight: bold;color: #000000;
">{{ des}}</h2>
                <!--<button class="btn">Continue</button> -->
            </div>
        </div>
    </div>
    {% endfor %}
    <ul class="pagination justify-content-start pagination-xsm m-0">
        <li class="page-item">
            <a class=" btn btn-primary page-link" href="{% url 'rankings_acad' %}" aria-label="Next">
                <span>View More</span>
            </a>
        </li>
    </ul>
    {% endif %}
    {% if rankings_P %}
    <div class="page-separator">
        <div class="page-separator__text">Personality</div>
    </div>
    {% for index, rank, des in rankings_P %}
    <div class="courses-container">
        <div class="course">
            <div class="course-preview">
                <h6 style="color: #ffffff;font-size: 1.3rem;">#{{index}}</h6>
                <h2 class="" style="color: #ffffff;font-size: 1.5rem;">{{rank}}</h2>
            </div>
            <div class="course-info">
                <h6>Description</h6>
                <h2 class="rank-h2 text" style="
    font-size: 1.2em;margin-block-start: 0.83em; margin-block-end: 0.83em; margin-inline-start: 0px;margin-inline-end: 0px;font-weight: bold;color: #000000;
">{{ des}}</h2>
                <!--<button class="btn">Continue</button> -->
            </div>
        </div>
    </div>
    {% endfor %}
    <a href="{% url 'rankings_pers' %}">View all rankings by Personality <i class="fas fa-chevron-right"></i></a>
    {% endif %}
    {% if rankings_KSP %}
    <div class="page-separator">
        <div class="page-separator__text">Academic Performance and Personality</div>
    </div>
    {% for index, rank, des in rankings_KSP %}
    <div class="courses-container">
        <div class="course">
            <div class="course-preview">
                <h6 style="color: #ffffff;font-size: 1.3rem;">#{{index}}</h6>
                <h2 class="" style="color: #ffffff;font-size: 1.5rem;">{{rank}}</h2>
            </div>
            <div class="course-info">
                <h6>Description</h6>
                <h2 class="rank-h2 text" style="
    font-size: 1.2em;margin-block-start: 0.83em; margin-block-end: 0.83em; margin-inline-start: 0px;margin-inline-end: 0px;font-weight: bold;color: #000000;
">{{ des}}</h2>
                <!--<button class="btn">Continue</button> -->
            </div>
        </div>
    </div>
    {% endfor %}
    <ul class="pagination justify-content-start pagination-xsm m-0">
        <li class="page-item">
            <a class="page-link" href="{% url 'rankings_both' %}" aria-label="Next">
                <span>View More</span>
            </a>
        </li>
    </ul>
    {% endif %}
</div>
<script src="{% static 'js/ranking.js' %}"></script>
<script type="text/javascript">
var backButton = document.getElementById("backbtn");
backButton.style.display = "none";
</script>
{% endblock %}

recommendation_sys/templates/recommendation_sys/studentdashboard.html
{% extends "personality/base.html" %}
{% load static %}
{% block body_block %}

<div class="page-section border-bottom-2" style="padding-bottom: 40%;">
    <div class="container page__container">
        <div class="card">
            <img src={% static "/images/paths/typescript_892x286.png" %} alt="TypeScript" class="card-img" style="max-height: 100%; width: initial;">
            <div class="fullbleed bg-primary" style="opacity: .5;"></div>
            <div class="card-body d-flex align-items-center justify-content-center fullbleed">
                <div>
                    <h2 class="text-white mb-16pt">Welcome to CAP framework</h2>
                    <div class="d-flex align-items-center mb-16pt justify-content-center">
                        <div class="d-flex align-items-center mr-16pt">
                            <p class="flex text-white-50 lh-1 mb-0"></p>
                        </div>
                        <div class="d-flex align-items-center">
                            <p class="flex text-white-50 lh-1 mb-0"></p>
                        </div>
                    </div>
                    <div class="d-flex align-items-center justify-content-center">
                        <a href="{% url 'personality:take' %}" class="btn btn-white mr-8pt">Personality Test</a>
                        <a href="{% url 'rankings' %}" class="btn btn-white mr-8pt">Recommend Career</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}